# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8569a1b959911eee5d6862364194498b9fbd71a540555f2289937b613e897c348da247add16bc518f8f5ceaa0887ca4accf64b74ab431acd7ecc867907e7cc

test:
  secret_key_base: af4db54804aec4f00ead67f6b2b0c03b9e2cc2e11e9afb10a0a71e1c8f77c9d7ec8d71e9c665c20a242b04c9a4c33e78f76750ebbd3e8a6dfdf5713365d001bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
